[package]
name = "gob"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]

[dependencies]
bytes = "0.4.6"
serde = "1.0.39"
serde_derive = "1.0.42"

[dev-dependencies]
serde_bytes = "0.10.4"
