[package]
name = "gob"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]

[dependencies]
bytes = "0.4.6"
lazy_static = "1.0.0"
serde = "1.0.39"
serde_derive = "1.0.42"
serde_schema = { path = "serde_schema", features = ["bytes"] }
slice-deque = { git = "https://github.com/gnzlbg/slice_deque.git" }
smallvec = "0.6.1"

[dev-dependencies]
duct = "0.10.0"
failure = "0.1.1"
tempfile = "3"
serde_bytes = "0.10.4"

[workspace]
members = ["serde_schema"]
